import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      collapsible: false,
      items: [
        'overview/intro',
        'overview/when-to-use',
        {
          type: 'category',
          label: 'Core Components',
          collapsed: false,
          collapsible: true,
          items: [
            'overview/data-modeling',
            'overview/event-store',
            'overview/network-providers',
            'overview/transport-layer',
            'overview/system-models',
            'overview/mempool-monitoring',
          ],
        },
        'overview/vs-alternatives',
        {
          type: 'category',
          label: 'Practical Guides',
          collapsed: true,
          collapsible: true,
          items: ['overview/quickstart', 'overview/first-custom-model'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-started',
        },
      ],
    },
    'examples',
  ],
};

export default sidebars;
