import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // 'index',
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      collapsible: false,
      items: [
        'overview/intro',
        'overview/data-modeling',
        'overview/network-providers',
        'overview/mempool-monitoring',
        'overview/transport-layer',
        'overview/event-store',
        'overview/system-models'
      ]
    },
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-started'
        }
      ]
    },
    'examples',
    // {
    //   type: 'category',
    //   label: 'Tutorials',
    //   collapsed: false,
    //   collapsible: false,
    //   items: []
    // },
  ],
};

export default sidebars;
